name: Deploy Suetolog Bot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости проекта

      - name: Create config.json from secrets
        run: |
          cat <<'EOF' > pidor-of-the-day-af3dd140b860.json
          ${{ secrets.CONFIG_JSON }}
          EOF

      - name: Create config.json from secrets
        run: |
          cat <<'EOF' > paswords.py
          ${{ secrets.PASWORDS_PY }}
          EOF

#      - name: Create passwords.py from secrets
#        run: |
#          echo "yadisk_token = \"${{ secrets.YADISK_TOKEN }}\"" > paswords.py
#          echo "yandex_gpt_catalog_id = \"${{ secrets.YANDEX_GPT_CATALOG_ID }}\"" >> paswords.py
#          echo "yandex_gpt_api_key = \"${{ secrets.YANDEX_GPT_API_KEY }}\"" >> paswords.py

      - name: Запуск тестов
        run: |
          pytest -m asyncio

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Вход на сервер по SSH и деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Переходим в директорию с проектом
            cd /root/suetolog_bot
            # Обновляем репозиторий
            git pull origin main
            # Останавливаем и удаляем контейнер с именем suetolog-bot, если он существует
            docker rm -f suetolog-bot || true
            docker rmi -f suetolog-bot || true
            docker build -t suetolog-bot .
            docker run -d --name suetolog-bot -v /root/suetolog_bot:/app suetolog-bot
